export const ADD_TODO = 'ADD_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const IMPORTANT_TODO = 'IMPORTANT_TODO'
export const SEARCH_TODO = 'SEARCH_TODO'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const ADD_USER = 'ADD_USER'